-- ============================================================================
-- Content Factory Schema Expansion (Phase 4)
-- Purpose: Support Drafts, Video Assets, and Multi-Language Publishing
-- ============================================================================

-- 1. Script Structure (JSONB)
-- Stores the Hook, Body, CTA, and other metadata from the LLM
ALTER TABLE content_queue
ADD COLUMN IF NOT EXISTS script_content JSONB DEFAULT '{}'::jsonb;

-- 2. Video Assets
-- URL to the rendered video file (S3/Supabase Storage) & Thumbnail
ALTER TABLE content_queue
ADD COLUMN IF NOT EXISTS video_url TEXT,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;

-- 3. Social Metadata
-- Caption and Hashtags generated by AI
ALTER TABLE content_queue
ADD COLUMN IF NOT EXISTS social_caption TEXT,
ADD COLUMN IF NOT EXISTS hashtags TEXT[];

-- 4. Localization & Targeting
-- Language of the asset (de, en, es) and target platforms
ALTER TABLE content_queue
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'de',
ADD COLUMN IF NOT EXISTS target_platforms TEXT[] DEFAULT '{}';

-- 5. Workflow State Tracking
-- Optional: More granular status tracking if needed (e.g. 'RENDERING', 'PUBLISHING')
-- We rely on existing 'status' column but might add check constraint updates if needed.
-- For now, we just add the columns.
